name: Checking and Fixing Code Style

on: [ push ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP_CS_Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs

      - name: Commit new changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Code style Fixed
